spring:
  datasource:
    url: jdbc:mysql://localhost:3306/klunker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

Server:
  servlet:
    context-path: /LenoLog
    port: 8080